universe                = docker
docker_image            = ncbi/sra-tools:latest

# --- THE FIX: Force Docker to use the basic shell ---
executable              = /bin/sh
arguments               = run_sra_test.sh SRR17720186

transfer_input_files    = run_sra_test.sh
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

stream_output           = True
stream_error            = True
output                  = sra_test_$(Cluster)_$(Process).out
error                   = sra_test_$(Cluster)_$(Process).err
log                     = sra_test_$(Cluster)_$(Process).log

request_cpus            = 4
request_memory          = 16GB
request_disk            = 100GB

queue 1
